---
  - name: Update apt
    apt:
      update_cache: true
      cache_valid_time: 3600

  - name: Enable IPv4 fowarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes 

  - name: Install iptables persisent
    apt:
      name: iptables-persistent
      state: latest

  - name: Install obfs4proxy
    apt:
      name: obfs4proxy
      state: latest

